// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wiqumzgfohxllyxmxkbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpcXVtemdmb2h4bGx5eG14a2J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTU1NDAsImV4cCI6MjA3MjM5MTU0MH0.9VBXkEAGAiEEZZcUFcwQBEmQILhXs2MTeYHFPO-bFvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});